### ISSUE TITLE
support wails template command

### ISSUE THREAD

**Issue by gedw99** [PylotLight/wails-htmx-templ-template#5]
Hey @PylotLight 

As per https://wails.io/docs/next/community/templates/

For example, https://github.com/misitebao/wails-template-vue is how it needs to look, if we want devs to be able to use this as a template.

wails init -n "Your Project Name" -t https://github.com/misitebao/wails-template-vue

**Comment by gedw99** [comment]
closing. it works fine ... sorry :)

**Comment by PylotLight** [comment]
FYI any repo link is valid. There's no check/criteria on the repo name.
