### ISSUE TITLE
makefile

### ISSUE THREAD

**Issue by gedw99** [PylotLight/wails-htmx-templ-template#9]
hey @PylotLight 

can you have a look at this and tell me why I cant build ?

https://github.com/gedw99/wails-htmx-templ-template

I dont use wails that much, and just wanted to kick the tires on this...

**Comment by PylotLight** [comment]
Did you get a specific build error? 
This isn't really quite clear.

**Comment by PylotLight** [comment]
I haven't seen any issues here. Also given others are fine I assume there's an issue with your env, if anything. Find us on the discord if you need anything else.
